# Generated by Django 4.2.3 on 2023-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_about_me_customuser_favorite_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
