# Generated by Django 4.2.3 on 2023-07-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('directions', models.TextField()),
                ('cooking_time', models.PositiveIntegerField(null=True)),
                ('star_count', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('recipe_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('drink', 'Drink'), ('cocktail', 'Cocktail'), ('other', 'Other')], max_length=100)),
                ('adapted_link', models.URLField(blank=True, default=None, null=True)),
                ('servings', models.PositiveIntegerField(null=True)),
                ('yield_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('allergens', models.TextField(blank=True)),
                ('small_desc', models.TextField(default='No Description has been added currently.', max_length=200)),
                ('pic', models.ImageField(default='no_picture.jpg', upload_to='recipe')),
            ],
        ),
    ]
