# Generated by Django 4.2.3 on 2023-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
