# Generated by Django 4.2.3 on 2023-07-27 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calorie_content', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_type', models.CharField(choices=[('cup', 'Cup'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon'), ('fluid ounce', 'Fluid Ounce'), ('pint', 'Pint'), ('quart', 'Quart'), ('gallon', 'Gallon'), ('milliliter', 'Milliliter'), ('liter', 'Liter'), ('ounce', 'Ounce'), ('pound', 'Pound'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('each', 'Each'), ('other', 'Other')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(max_length=255)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient')),
            ],
        ),
    ]
